# Generated by Django 4.2.6 on 2023-10-10 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=64)),
                ('task_description', models.CharField(max_length=500)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('task_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
