# Generated by Django 4.2.6 on 2023-10-10 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_user_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
